name: flutter_mcp_common
description: Common utilities and platform integrations for Model Context Protocol (MCP) in Flutter applications
version: 0.0.2
homepage: https://github.com/app-appplayer/flutter_mcp_common

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  flutter_local_notifications: ^15.1.0+1
  flutter_background_service: ^5.0.5
  path_provider: ^2.1.1
  uuid: ^4.0.0
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appplayer.flutter_mcp_common
        pluginClass: FlutterMcpCommonPlugin
      ios:
        pluginClass: FlutterMcpCommonPlugin
      web:
        pluginClass: FlutterMcpCommonWeb
        fileName: flutter_mcp_server_web.dart
      macos:
        pluginClass: FlutterMcpCommonPlugin
      windows:
        pluginClass: FlutterMcpCommonPluginCApi
      linux:
        pluginClass: FlutterMcpCommonPlugin

